package com.fongmi.android.tv.player.danmaku;

import androidx.media3.datasource.HttpDataSource;

import java.io.IOException;

/** Keeps retries useful and bounded; a timeout is never repeated behind the user's back. */
public final class DanmakuLoadPolicy {

    static final int MAX_SAME_SOURCE_RETRIES = 2;

    private DanmakuLoadPolicy() {
    }

    public static boolean shouldRetry(IOException error, int retryCount) {
        if (retryCount >= 1 || error == null) return false;
        int responseCode;
        if (error instanceof HttpDataSource.InvalidResponseCodeException) {
            responseCode = ((HttpDataSource.InvalidResponseCodeException) error).responseCode;
        } else if (error instanceof DanmakuDocumentCache.HttpStatusException) {
            responseCode = ((DanmakuDocumentCache.HttpStatusException) error).statusCode();
        } else {
            return false;
        }
        return shouldRetryResponseCode(responseCode);
    }

    /**
     * A comment id is generated by the search service and can briefly be rate limited. Retry the
     * same id only for 408/429; a 5xx normally means that generated id is bad and the catalogue
     * must be searched again to obtain a fresh one.
     */
    static boolean shouldRetrySameSource(IOException error, int retryCount) {
        if (retryCount >= MAX_SAME_SOURCE_RETRIES) return false;
        int responseCode = responseCode(error);
        return responseCode == 408 || responseCode == 429;
    }

    static long sameSourceRetryDelayMillis(IOException error, int retryCount) {
        if (!shouldRetrySameSource(error, retryCount)) return -1L;
        long fallback = retryCount == 0 ? 2_500L : 6_000L;
        if (error instanceof DanmakuDocumentCache.HttpStatusException) {
            long retryAfter = ((DanmakuDocumentCache.HttpStatusException) error).retryAfterMillis();
            if (retryAfter > 0) return Math.max(fallback, Math.min(retryAfter, 15_000L));
        }
        return fallback;
    }

    /** A stale/transient manual selection should be resolved through search, not persisted. */
    public static boolean shouldRefreshSource(IOException error) {
        int responseCode = responseCode(error);
        return responseCode == 404 || shouldRetryResponseCode(responseCode);
    }

    private static int responseCode(IOException error) {
        if (error instanceof HttpDataSource.InvalidResponseCodeException) {
            return ((HttpDataSource.InvalidResponseCodeException) error).responseCode;
        }
        if (error instanceof DanmakuDocumentCache.HttpStatusException) {
            return ((DanmakuDocumentCache.HttpStatusException) error).statusCode();
        }
        return -1;
    }

    static boolean shouldRetryResponseCode(int responseCode) {
        return responseCode == 408 || responseCode == 429 || responseCode >= 500;
    }
}
